package com.netra.commons.enums;


import static com.netra.commons.enums.DisputeState.*;

public enum BlockchainEventType {
    DISPUTE_CREATED_BCE(0, BOOTSTRAP_DISPUTE_CONTEXT),
    EVIDENCE_SUBMITTED_BCE(1, AWAITING_EVIDENCE_VERIFICATION),
    EVIDENCE_ACCEPTED_BCE(2, EVIDENCE_VERIFIED),
    EVIDENCE_REJECTED_BCE(3, EVIDENCE_REJECTED) ,
    PLAINTIFF_VERIFIED_BCE(4, PLAINTIFF_VERIFIED),
    PLAINTIFF_DECLINED_BCE(5,PLAINTIFF_DECLINED),
    RESPONDER_VERIFIED_BCE(6, RESPONDER_VERIFIED),
    RESPONDER_DECLINED_BCE(7, RESPONDER_DECLINED),
    ARBITRATION_INITIATED_BCE(8, ARBITRATION_PROCESSOR_AWAITING_RESPONSE),
    ARBITRATION_RULED_PLAINTIFF_BCE(9, ARBITRATION_PROCESSOR_RESOLVED_PLAINTIFF_FAVOR),
    ARBITRATION_RULED_RESPONDER_BCE(10, ARBITRATION_PROCESSOR_RESOLVED_RESPONDER_FAVOR),
    ARBITRATION_AMBIGUOUS_BCE(11, ARBITRATION_PROCESSOR_RESOLVED_AMBIGUOUS),
    MANUAL_ARBITRATION_RULED_PLAINTIFF_BCE(12, ARBITRATION_MANUAL_RESOLVED_PLAINTIFF_FAVOR),
    MANUAL_ARBITRATION_RULED_RESPONDER_BCE(13,ARBITRATION_MANUAL_RESOLVED_RESPONDER_FAVOR),
    MANUAL_ARBITRATION_AMBIGUOUS_BCE(14, ARBITRATION_MANUAL_RESOLVED_AMBIGUOUS),
    AUTHORITY_ESCALATED_PLAINTIFF_BCE(15,AUTHORITY_PLAINTIFF_ESCALATED),
    AUTHORITY_ESCALATED_RESPONDER_BCE(16, AUTHORITY_RESPONDER_ESCALATED),
    AUTHORITY_ESCALATED_SYSTEM_BCE(17, AUTHORITY_SYSTEM_ESCALATED),
    WITHDRAWN_BY_CUSTOMER_BCE(18,WITHDRAWN_CUSTOMER),
    WITHDRAWN_BY_PLAINTIFF_BCE(19, WITHDRAWN_PLAINTIFF),
    WITHDRAWN_BY_RESPONDER_BCE(20,WITHDRAWN_RESPONDER),
    WITHDRAWN_DURING_ARBITRATION_BCE(21, WITHDRAWN_ARBITRATION),

    WITHDRAWN_BY_SUB_INSTITUTION_BCE(22, WITHDRAWN_SUB_INSTITUTION),
    DISPUTE_EXPIRED_BCE(23, EXPIRED),
    DISPUTE_CLOSED_BCE(24, CLOSED);

    private final int numericRep;
    private final DisputeState assumedState;
    BlockchainEventType(int numericRep, DisputeState assumedState){
        this.assumedState = assumedState;
        this.numericRep = numericRep;
    }
}
