package com.netra.commons.enums;

public enum DisputeState {
    ACCEPT,
    DECLINE,
    EXPIRE,
    WITHDRAW,
    REOPEN,
    EVIDENCE_REJECTED,
    EVIDENCE_ENRICHED,
    INITIATED,
    ISSUER_REQUESTED,
    ISSUER_REJECTED,
    ISSUER_CONFIRMED,
    ACQUIRER_NOTIFIED,
    ACQUIRER_ACCEPTED,
    ACQUIRER_DECLINED,
    ACQUIRER_REJECTED,
    ESCALATED,
    RESOLVED,
    CLOSED;
}
